addr: ':8609'
application: "You photo service"
instance: "main"
datasource:
  sqlite:
    type: sqlite
    path: './data/database.db'
service:
  name: "yps"
  display: "YouPhoto service"
youplus:
  auth: false
  enablepath: false
  enablerpc: false
  url: 'http://localhost:8999'
  rpc: 'localhost:50055'
  entity:
    enable: false
    name: "youplus"
    version: 1
log:
  youlog:
    application: "YouPhoto"
    instance: "main"
    engine:
      local:
        type: logrus
      logservice:
        type: youlogservice
        address: "localhost:60376"
      fluentd:
        type: fluentd
        url:  "http://localhost:53373"
thumbnails:
  provider: "local"
  enable: false
  service_url: "http://localhost:8020"
  store_path: "./data/thumbnails"
register:
  enable: false
  endpoints:
    - localhost:12379
  regpath: ./reg.yml
auth:
  youauth:
    enable: false
    type: youauth
    url: "http://localhost:8602"
    appid: "appid"
    secret: "secret"

  youplus:
    type: youplus
    enable: true

